SELECT * FROM MANUFACTURINGG;

SELECT CUST_CODE FROM MANUFACTURINGG;



SELECT * FROM MANUFACTURINGG;

#1.Manufacturing Quantity (Total)
SELECT SUM(TODAY_MANUFACTURED_QTY) AS TOTAL_MANUFACTURING_QTY
FROM MANUFACTURINGG;

#2.TOTAL Rejected Quantity 
SELECT SUM(REJECTED_QTY) AS TOTAL_REJECTED
FROM MANUFACTURINGG;

#3. TOTAL Processed Quantity 
SELECT SUM(Processed_QTY) AS TOTAL_Processed
FROM MANUFACTURINGG;

#4. TOTAL Wastage Quantity
SELECT SUM(WO_QTY) AS TOTAL_WASTAGE
FROM MANUFACTURINGG;

#5. Employee Wise Rejected Quantity
SELECT EMP_NAME, SUM(REJECTED_QTY) AS EMPLOYEE_WISE_REJECTED_QTY
FROM MANUFACTURINGG
GROUP BY EMP_NAME
ORDER BY EMPLOYEE_WISE_REJECTED_QTY DESC;

#6. Department Wise Manufacture vs Rejected
SELECT 
    DEPARTMENT_NAME,
    SUM(TODAY_MANUFACTURED_QTY) AS TOTAL_MANUFACTURED,
    SUM(REJECTED_QTY) AS TOTAL_REJECTED,
    ROUND(SUM(REJECTED_QTY) / SUM(TODAY_MANUFACTURED_QTY) * 100, 2) AS REJECTED_BY_DEPT
FROM MANUFACTURINGG
GROUP BY DEPARTMENT_NAME
ORDER BY REJECTED_BY_DEPT DESC;






